name: CI
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI on (Python ${{ matrix.python-version }})
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout the source
        uses: actions/checkout@v3
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install tox
        run:
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox
        env:
          PW_USER_TOKEN: ${{ secrets.PW_USER_TOKEN }}
        run:
          tox
